// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRHY5zC5j5rncbj287LlOQRLG9CibsIl0',
    appId: '1:314740040837:android:598274248aee9a292735ec',
    messagingSenderId: '314740040837',
    projectId: 'food-102a1',
    storageBucket: 'food-102a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QnaKukLWHeWXA5-e3pe9EtogSTMVJi4',
    appId: '1:314740040837:ios:f9c4846ac91c0be52735ec',
    messagingSenderId: '314740040837',
    projectId: 'food-102a1',
    storageBucket: 'food-102a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJsN0zRB8sBtmxfK190YJ8hpyYOGvn7s',
    appId: '1:314740040837:web:44e04824cdf557012735ec',
    messagingSenderId: '314740040837',
    projectId: 'food-102a1',
    authDomain: 'food-102a1.firebaseapp.com',
    storageBucket: 'food-102a1.firebasestorage.app',
    measurementId: 'G-519C8HFJ78',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeJsN0zRB8sBtmxfK190YJ8hpyYOGvn7s',
    appId: '1:314740040837:web:e7b785574b64d3e12735ec',
    messagingSenderId: '314740040837',
    projectId: 'food-102a1',
    authDomain: 'food-102a1.firebaseapp.com',
    storageBucket: 'food-102a1.firebasestorage.app',
    measurementId: 'G-KYH00FWE9L',
  );

}