// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjFPIh-ez8eEHVfh6M_faKulNiwtxJUqE',
    appId: '1:352822451431:web:d73251f99a13c46ae4d642',
    messagingSenderId: '352822451431',
    projectId: 'chat-76abf',
    authDomain: 'chat-76abf.firebaseapp.com',
    storageBucket: 'chat-76abf.firebasestorage.app',
    measurementId: 'G-9N2EDF6JWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvN_VJJ0WHg5YYZIAzXoAmCSmsDlsvVDE',
    appId: '1:352822451431:android:e162053cacc3132fe4d642',
    messagingSenderId: '352822451431',
    projectId: 'chat-76abf',
    storageBucket: 'chat-76abf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu31WY6Gpw9BIyXuuEUZNBIufApfGiZ0Y',
    appId: '1:352822451431:ios:0bd5e1349be3b7d4e4d642',
    messagingSenderId: '352822451431',
    projectId: 'chat-76abf',
    storageBucket: 'chat-76abf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjFPIh-ez8eEHVfh6M_faKulNiwtxJUqE',
    appId: '1:352822451431:web:1065c447a19b8a76e4d642',
    messagingSenderId: '352822451431',
    projectId: 'chat-76abf',
    authDomain: 'chat-76abf.firebaseapp.com',
    storageBucket: 'chat-76abf.firebasestorage.app',
    measurementId: 'G-C0FXQX7RKV',
  );
}
